### ISSUE TITLE
`node@0.04` compatibility 

### ISSUE THREAD

**Issue by paoloricciuti** [PuruVJ/neotraverse#1]
This package doesn't seem to be compatible with `node@0.04` which is exactly what I needed. Is it possible to be compatible with it?

I'm willing to make a PR for it but I will likely need to bring some dependencies. That could also help with security since currently this package is at risk of someone messing with the prototype of native objects.

**Comment by PuruVJ** [comment]
Good idea. Could you install the deps using pip3 though? I'm so tired of node_modules bloat. Lets rewrite this in python and ship a WASM binary :DDD

**Comment by sukeshpabolu** [comment]
@paoloricciuti you should submit a PR with 100 chungus of dependencies then only it is acceptable

**Comment by andrewdoro** [comment]
bro, i got the solution, will just rewrite this in c, then use node bindings

**Comment by kibertoad** [comment]
@paoloricciuti You'd need to introduce custom GitHub Actions to be able to run tests for that. And you better rewrite them in tape

**Comment by PuruVJ** [comment]
I don't have a heart to close this. Pinning it to the top 🤣

EDIT: It seems it stays pinned even after being closed so will close this, but good thread 😄

**Comment by paoloricciuti** [comment]
> I don't have a heart to close this. Pinning it to the top 🤣
> 
> EDIT: It seems it stays pinned even after being closed so will close this, but good thread 😄

Lol
