### ISSUE TITLE
Question: How to combine Jest & Neotraverse?

### ISSUE THREAD

**Issue by thim81** [PuruVJ/neotraverse#8]
When trying to migrate from Traverse to Neotraverse, using `import traverse from 'neotraverse';` in a Typescript project, Jest complains with this error:

```
Jest encountered an unexpected token

Jest failed to parse a file. This happens e.g. when your code or its dependencies use non-standard JavaScript syntax, or when Jest is not configured to support such syntax.

Out of the box Jest supports Babel, which will be used to transform your files into valid JS based on your Babel configuration.

node_modules/neotraverse/dist/min/index.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,jest){......

SyntaxError: Unexpected token 'export'
```

Not being a Typescript, any pointers would be helpful and appreciated.

**Comment by PuruVJ** [comment]
Jest doesn't support ESM unfortunately, which is the only format neotraverse ships with. Replace the import with `neotraverse/legacy` and it should work

**Comment by thim81** [comment]
hi @PuruVJ 

I'm trying your suggestion in a Typescript project and using `import traverse from 'neotraverse/legacy'`

Next question, where I would need your assistance:
```
TS7016: Could not find a declaration file for module neotraverse/Legacy •
/node_modules/neotraverse/legacy.js
implicitly has an any type.
```

and 
```
TS2683: 'this' implicitly has type 'any' because it does not have a type annotation.
```
I'm using `"neotraverse": "^0.6.12"`

**Comment by PuruVJ** [comment]
Which TypeScript version are you using?

**Comment by thim81** [comment]
We are using ` "typescript": "^4.3.4"`

**Comment by PuruVJ** [comment]
Strange. Could you make a small reproduction in a github repo? It'll help me debug the issue

**Comment by PuruVJ** [comment]
Wait I think I know. TypeScript 4.5+ started reading export maps in package.json, hence your version isn't able to find the types. Lemme push a patch.

**Comment by thim81** [comment]
I m making a PR, so I ll push that in about 1h.

**Comment by PuruVJ** [comment]
Any chance you could upgrade to TS 4.5?

**Comment by thim81** [comment]
Let me give it a try.

**Comment by thim81** [comment]
@PuruVJ an update: the package.json showed "typescript": "^4.3.4" but actually  "typescript": "^4.9.5" was installed.

Should I bump it to a specific version or 5.x?

**Comment by PuruVJ** [comment]
Should be fine now, try 0.6.13

**Comment by PuruVJ** [comment]
> the package.json showed "typescript": "^4.3.4" but actually "typescript": "^4.9.5" was installed.

That makes things stranger 😅. Either way try 0.6.13, restart ur editor and lemme know if it worked this time.

Note: if you are using require(neotraverse/legacy), you won't get typings. You'll have to assert the variable to `as import('neotraverse/legacy')['default']`

**Comment by thim81** [comment]
I've just pushed the PR https://github.com/apideck-libraries/portman/pull/615

I'll check the test results and correct where necesary.

**Comment by PuruVJ** [comment]
I posted a comment there
